### PR TITLE
Dynamic ra dec

### PR DESCRIPTION
**Pull request by metaml**
(description added by @Siltala ) 

For context, this PR implements astrometric weighting for MPC observations inside openorb with the statistical error model of Baer & Chesley 2017.

### CODE REVIEW

**Comment by metaml** [comment]
Hi, Lauri: please review. Thanks!

**Comment by Siltala** [comment]
A couple of comments (more will come):
 
- Please clean the commit history a bit, I see there was a messy rebase in particular - https://github.com/oorb/oorb/pull/170/commits/b982bc8a211f3825f2474ec53bf3ac68f186bfc3 especially includes over 12k lines of "new" code.
I would also squash commits that work on the same feature together if that makes sense, for instance I see three separate nix flake related commits that could be squashed into a single one (and perhaps the bash stuff moved to a separate commit) All this will make review much simpler for us also.

- You named your new configuration file option `stats.err` whereas in `readConfigurationFile` you look for the option `stats.err_file`.
I think that it's misnamed in one place?

- I think it's a bit cumbersome to pass around `stats_err_file` as an additional function parameter so heavily, and I would like to avoid that. My suggestion is to define the variable in the type definition by adding the following line after line 122:
```LOGICAL               :: stats_err_file = .FALSE.```
This way, any subroutine inside the Observations class will be available to read it directly and you don't have to pass it on to other functions all the time. Then I think you can just remove line 312 and `stats_err_file` from the function arguments (other than `NEW_Obss_file` anyways, where you change it to .TRUE. if the configuration is set to be so) and it should work.

- Unless I'm doing something horribly wrong, the code doesn't actually seem to work for me. It does compile, but by testing it with 
```./oorb --task=obs2des --obs-in= ../test/K08K42V_lsl.mpc``` one can see that the covariances are set to 1 (the default for `stdev.ra` and `stdev.dec` in the configuration file) rather than what the error model has.

- I don't know if `modules/stats_err.f90` is the right place for this code or not and whether it should be a type or not as you set it. I'll discuss this with @mgranvik during our next chat.

Many thanks for your work, I'm very excited to get something like this in oorb!

**Comment by metaml** [comment]
- Yeah, I'll clean up my commit. I didn't see the squash button when creating a PR
- stats.err_file is intentional. If you rename it, you'll need to make changes to the code
- I think I understand what you mean by stats_err_file. I change it to that. Thanks!
- ./oorb --task=obs2des ... the magnitude values are out of range from what's in the data file
- module vs. classes, it wasn't clear to me the distinction in oorb. I opted for the functional approach but let me where it should live

**Comment by metaml** [comment]
Closing this PR as it's easier to create a new branch and submit a new PR taking into account Siltala's comments.

**Pull request closed without merging**
