### PR TITLE
Datafile IO updates

### PR DESCRIPTION
**Pull request by Siltala**
This PR adds a possible solution to #118 . It uses the resolveDirectory to check PREFIX/share/oorb for the gnuplot scripts -if- OORB_GNUPLOT_SCRIPTS_DIR is not defined.

Similarly, resolveDirectory has been copied to planetary_data.f90 (because Base_class.f90 is not included there, and presumably you don't want to do so) and is used there to check the same directory for the BC430 files if OORB_DATA is not defined. It adds prefix.h as an include because the PREFIX is stored there.

Let me know if you're not happy with this and I'll see if I can adjust things.

### CODE REVIEW

**Comment by Siltala** [comment]
Aand the ephemeris building is failing as in my previous PR, which I'm sure has nothing to do with this one. I'll investigate since it apparently wasn't just a one-off thing.

**Comment by mgranvik** [comment]
@mjuric and @rhiannonlynne, does this pose problems on your side? That is, are you relying on the default behaviour or are you setting env vars explicitly?

**Comment by Siltala** [comment]
This PR now moves resolveDirectory from Base_class.f90 to utilities.f90, making it accessible to planetary_data in addition to everywhere else. This avoids code duplication (original message mentions that I copied resolveDirectory to planetary_data at first) so it's a bit cleaner now without breaking any existing functionality.

To clarify, the behavior for most data files (everything except BC430 and the gnuplot scripts) is:

- Look for data in OORB_DATA
- If the above variable is not defined, look for the data in PREFIX/share/oorb instead

This part is unchanged by the PR.

old behavior for the gnuplot scripts is:

- Look for them in OORB_GNUPLOT_SCRIPTS_DIR

New behavior introduced with this PR is

- Look for them in OORB_GNUPLOT_SCRIPTS_DIR
- If the above variable is not defined, look for the data in PREFIX/share/oorb instead

Similarly, the old behavior for reading BC430 files is:

- Look for data in OORB_DATA

while with this PR it becomes

- Look for data in OORB_DATA
- If the above variable is not defined, look for the data in PREFIX/share/oorb instead

PREFIX is, of course, an argument given to the configure script during compilation time.

**Comment by Siltala** [comment]
One small thought/question regarding this PR that needs to be answered before merging is: does PREFIX/share/oorb make sense as a location for the gnuplot scripts to begin with or should they be in their own folder (e.g. PREFIX/share/oorb/gnuplot?

The other data files are simply at PREFIX/share/oorb rather than e..g  PREFIX/share/oorb/data (as detailed in my previous comment) so I personally think it would make sense to also have the gnuplot scripts there (as the PR currently does things).

**Comment by mgranvik** [comment]
I would go with PREFIX/share/oorb/gnuplot for gnuplot scripts and PREFIX/share/oorb for the data files.

**Comment by Siltala** [comment]
Updated the PR to match the requested behavcior (now uses PREFIX/share/oorb/gnuplot for gnuplot scripts)

**Comment by mjuric** [comment]
Hi all -- apologies for missing the @ on this PR -- just to confirm this looks great from the LSST PoV (and also the conda package PoV). Having a standard default for all data files makes it much easier for a user.

Thanks for implementing this!

**Pull request merged**
