### PR TITLE
update obscode data

### PR DESCRIPTION
**Pull request by caditi97**
This pull request runs [updateOBSCODE](https://github.com/mjuric/oorb/blob/conda/data/updateOBSCODE) which is a utility script that downloads the most recent table of observatory coordinates. This is because we (me, Mario Juric, Sarah Greenstreet, Joachim Moeyens) are trying to update the conda functionality of openorb.

### CODE REVIEW

**Comment by mgranvik** [comment]
This PR seems to formally still be a work in progress. Is that on purpose?

**Comment by caditi97** [comment]
> This PR seems to formally still be a work in progress. Is that on purpose?

Yes, I just wanted to run the changes through other people before staging them.

**Comment by Siltala** [comment]
I guess there is no harm in updating the default OBSCODE.dat every once in a while since we do host the file in this repo, even though it is trivial for users to do this themselves locally with the script.

**Comment by mgranvik** [comment]
It seems that the OBSCODE.dat file has been updated as part of another pull request after this pull request was issued, so to keep things tidy I will close this pull request without accepting it.

**Pull request closed without merging**
